### ISSUE TITLE
Issue with navigation/header 

### ISSUE THREAD

**Issue by emfeather94** [emfeather94/kraken-good-accessibility#1] opened 2020-10-07 14:37 UTC
Hi! @HannahDelaney

I am having issues getting my header/navigation to work. I want to align my nav button with the title but can't seem to get it right...I've messed around with the code a bit too much I think at this point 😭. Also, markbot is also telling me "The contrast of the headers text isn't enough compared to the background colour" (I think someone else in the slack thread was having this issue as well).

Any help would be much appreciated! Thanks 😊 

Emily

**Comment by HannahDelaney** [comment] 2020-10-07 15:24
So this one is a bit tricky because the css is mostly applied and you sort of have to arrange your HTML based off of it, which is a bit counter to what we normally do.

Some things that might help with the nav:
There are 2 headers in this assignment, and the article needs to be moved up. The article should open after your first header, which closes after the name Jules Verne.

```
  <header role="banner">
    <strong>Twenty Thousand Leagues Under the Sea</strong>
    <p><span class="by">by</span> <span>Jules Verne</span></p>
  </header>
```

Open your article after these lines, and then your second header. There shouldn't be an article around the `<h1>` and `<h2>` (try the target `<hgroup>` [it's handy](https://www.w3docs.com/learn-html/html-hgroup-tag.html)). You also won't need the article around the big collection of `<p>` tags either. The header is fine to close where it currently does, and then your article can close after the first footer (there are also two footers!). The first footer has one nav, the second just the small content.

The classes you've added to the div tags, the "target" ones, won't be necessary. If you actually just fully remove all the `<div>`s that have the "target-1", "target-2" and "target-3" classes, you should be in good shape!

Make sense? That may give you other errors, but I'll let you try them out first. Hint: the `role="main"` doesn't HAVE to be on a `<main>` tag.

As for the `background-color` contrast issue, it is giving you trouble because we are learning about accessibility and the contrast with the type is currently being created with an image. If someone's browser can't display images, they won't be able to read it. When you use a `background-image` like is done here, you should also give a `background-color` as a backup option. Adding that to the places where there are background images should clear up that problem!

**Comment by HannahDelaney** [comment] 2020-10-07 15:26
This one is so nit-picky because the accessibility CSS content is prearranged based on your HTML semantics being exactly the same as the sample. But you were making good set up choices in your HTML! Let me know if you have any other issues.

**Comment by emfeather94** [comment] 2020-10-07 18:20
Hi Hanna! 

Thanks so much for all this feedback. I've tried taking into consideration everything you've listed however I am still running into the same issues (still background color error and navigation button)

I am not 100% sure what you mean by the 'main' not needing to be on the main tag... 

I appreciate your help :)

**Comment by HannahDelaney** [comment] 2020-10-07 18:27
Are you getting the error that `main` can't be the child of `article`? Your `<main role="main">` can just be `<div role="main">`, that's what I meant.

Hm. I applied all the changes I listed to your code and it fixed the errors on Markbot. Maybe I forgot to add part when describing it here. Did you add a `background-color` to the header that has a background image, as well as the footer, in the CSS?

**Comment by emfeather94** [comment] 2020-10-07 18:31
No I am not! It says it is ok.

Yes, maybe I wrote it wrong? 

header {
  background-image: url("../images/anchors.svg");
  background-color: #259f95;
  color: #fff;
  font-size: 1.125rem;
  font-style: normal;
  font-weight: normal;
  padding: 1rem 0 0;
}

and 

footer {
  display: flex;
  justify-content: center;
  padding: 1rem;
  background-image: url("../images/anchors.svg");
  color: #fff;
  background-color: #259f95;
}

**Comment by HannahDelaney** [comment] 2020-10-07 18:34
Looks good! I think the issue is the actual colour you chose. If you look at `#259f95` it's a bit light, so it's harder to read white text on. Try using `#1e7c74` and see if that fixes it.

**Comment by emfeather94** [comment] 2020-10-07 18:42
YAY! that worked! thanks!

Now just trying to get the nav up to the right side, but will give it a few attempts before seeking help again haha

**Comment by emfeather94** [comment] 2020-10-07 18:46
I got it :) thanks so much for your help, have a good one!

**Comment by HannahDelaney** [comment] 2020-10-07 18:46
Yay!

lolol sounds good. If it's really bothering you let me know and commit again, and I can look for any outlying issues or typos that might be getting at you.

Good luck! (Also if you solve it, don't forget to close the issue 😄 )

**Closed as completed** 2020-10-07 18:46 UTC
